### ISSUE TITLE
Buttons aren't completely on the screen

### ISSUE THREAD

**Issue by brousch** [bookieio/Bookie-Android#1]
The buttons at the bottom of the screen are partially cut off. I am using an LG Spectrum with Android 2.3.6. The screen is 1280x720. https://www.dropbox.com/s/xdxr4sntkogvo0e/2012-10-07%2009.28.39.jpeg

**Comment by mitechie** [comment]
I can confirm this on my Nexus 7 tablet which is 1280x800

**Comment by DerekV** [comment]
Those buttons need to go away in place of some better suited UI pattern.  Hopefully that can be a quick fix for this as well.

**Comment by DerekV** [comment]
Are the button's usable? I'm only asking so I can prioritize this.

**Comment by brousch** [comment]
Yes, they work corr6

**Comment by DerekV** [comment]
Is this solved for everyone on release 2?

**Comment by mitechie** [comment]
Looks good for me and I know Ben said so as well.
