### ISSUE TITLE
Should results show the description vs url field?

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie-Android#3]
This is kind of a question. It takes some parsing when looking at the urls and I wonder if the descriptions would be nice to use in the lists.

**Comment by DerekV** [comment]
My thinking is that description should be shown, or it should be configurable.

**Comment by DerekV** [comment]
Opened issue #5 , which is related.  I see this as more of a question of what should the list view itself look like/display ... 
- where is the sweet spot between ...
  *\* displaying more information
  *\* being easier to read (less dense)
  *\* having more bookmarks fit on the screen.  
- how do we decide what information to leave off (and provide in some sort of details or zoomed view ( ala issue #5 )

**Comment by widox** [comment]
Hm, I think just showing the bmark title; and the tags (maybe a good candidate for config option) would be good. Then maybe a long press could show the more detailed info. i.e. date saved, url, etc.

Additionally, I like having favicons for each bmark; makes it easier to parse and recognize bmarks. This is especially helpful when mobile.

**Comment by DerekV** [comment]
Thanks widox.  Regarding the favicons, agreed and opening a new issue #6

**Comment by mitechie** [comment]
I've put some thought into it and I think mirroring the UI in the web 'mobile' view would be good. It shows the tags, description, username, and controls in a three line format. I have always like the twitter swipe for controls UX though so perhaps just showing tags and description would be a good start at seeing info and that the username/controls would be some for a 'click on the row to view details' activity.
