### ISSUE TITLE
bookie icon in play store is off

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie-Android#4]
The bookie icon looks great on the device, but in the play store the icon seems to be missing the font or something.  

The font is http://www.google.com/webfonts/specimen/Cabin+Sketch

**Comment by DerekV** [comment]
Yep, fortunately that can be updated without doing an update of the app.

**Comment by DerekV** [comment]
Original issue is fixed.  Any art improvements/ideas can be a new ticket.

**Comment by DerekV** [comment]
On second thought, its still broken, just differently now.
